#!/bin/bash
#I dont care if this looks nice or not its a shell script to install neccery stuff
echo "Thanks for downloading roxysploit!"
echo "So im going to load all files now for you please wait..."
mv rsfc /usr/bin/rsfc
chmod +x /usr/bin/rsfc

mv rsfupdate /usr/bin/rsfupdate
chmod +x /usr/bin/rsfupdate

mkdir /opt/roxysploit
mv * /opt/roxysploit/
chmod +x /opt/roxysploit
mkdir /opt/roxysploit/storage/logs

echo "installing all packages..."
pip install logging
pip install impacket
pip install pysmb
pip install threading
pip install socket
pip install socks
pip install zipfile
pip install shutil
pip install io
pip install struct
pip install re
pip install optparse
pip install binascii
pip install base64
pip install urllib2
pip install urllib
pip install requests
pip install commands
pip install paramiko
pip install scapy
pip install whois
pip install rlcompleter
pip install readline
pip install terminaltables
pip install platform
dpkg --add-architecture i386 #needs this becuz we want wine32 boi XD
apt-get install wine32 #install wine32 i commented this because https://github.com/Eitenne/roxysploit/issues/3
apt-get -y install android-tools-adb android-tools-fastboot

echo "Ok were done :) run 'rsfc'"
